#!/bin/sh

# Set these paths appropriately

BIN=`pwd`/ner/tree_tagger/POS_tagging/bin
CMD=`pwd`/ner/tree_tagger/POS_tagging/cmd
LIB=`pwd`/ner/tree_tagger/POS_tagging/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
