#!/bin/sh

# Set these paths appropriately

BIN=`pwd`/ner/tree_tagger/POS_tagging/bin
CMD=`pwd`/ner/tree_tagger/POS_tagging/cmd
LIB=`pwd`/ner/tree_tagger/POS_tagging/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
